services:
  mysql:
    image: mysql:8.0
    container_name: rentas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rent_control
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rentas_backend
    restart: always
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: rent_control
      DB_USERNAME: root
      DB_PASSWORD: root
      SESSION_DRIVER: database
      CACHE_STORE: database
      QUEUE_CONNECTION: database

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: rentas_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
